# vault-values.yaml.tpl
# HashiCorp Vault ENTERPRISE — HA Raft + Azure Key Vault Auto-Unseal
# + Performance Replication + TLS (certs generated by Terraform)
#
# The TLS cert is generated in tls.tf, stored as the Kubernetes secret
# referenced by ${tls_secret_name}, and mounted at /vault/userconfig/vault-tls/
# via extraVolumes/extraVolumeMounts below.

global:
  enabled: true
  tlsDisable: false
  imagePullSecrets:
    - name: "${image_pull_secret_name}"

injector:
  enabled: true
  replicas: 2
  image:
    repository: "hashicorp/vault-k8s"
    tag: "1.4.0"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: vault-agent-injector
          topologyKey: kubernetes.io/hostname

server:
  image:
    repository: "hashicorp/vault-enterprise"
    tag: "${vault_version}"
    pullPolicy: IfNotPresent

  enterpriseLicense:
    secretName: "${license_secret_name}"
    secretKey: "license"

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

  readinessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true&perfstandbyok=true&uninitcode=204&sealedcode=204"
    scheme: HTTPS

  # Liveness probe disabled — enable after running vault operator init.
  # With auto-unseal via Azure Key Vault, Vault will unseal itself after init
  # and the readiness probe will start passing once the cluster is active.
  livenessProbe:
    enabled: false

  # Point the Vault CLI at the TLS certs and tell the Azure SDK which
  # managed identity to use. AZURE_CLIENT_ID is read by DefaultAzureCredential
  # before it hits the IMDS endpoint — without it, IMDS returns an error when
  # multiple user-assigned identities are present on the node.
  # AZURE_TENANT_ID lets EnvironmentCredential succeed as the first attempt,
  # falling back to ManagedIdentityCredential with the explicit client_id.
  extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/vault-tls/ca.crt
    VAULT_TLSCERT: /vault/userconfig/vault-tls/tls.crt
    VAULT_TLSKEY: /vault/userconfig/vault-tls/tls.key
    AZURE_CLIENT_ID: "${akv_client_id}"
    AZURE_TENANT_ID: "${akv_tenant_id}"

  # Mount the Terraform-generated TLS secret into every Vault pod
  extraVolumes:
    - type: secret
      name: vault-tls
      secretName: "${tls_secret_name}"
      defaultMode: "0400"

  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "vault"
      effect: "NoSchedule"

  nodeSelector:
    workload: vault

  # Force Vault pods to use CoreDNS (ClusterFirst) so private DNS zones
  # configured in the coredns-custom ConfigMap are resolvable by the
  # Vault process itself, not just other pods in the cluster.
  dnsPolicy: "ClusterFirst"
  dnsConfig:
    nameservers: []   # use CoreDNS automatically via ClusterFirst
    searches:
      - vault.svc.cluster.local
      - svc.cluster.local
      - cluster.local

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: vault
              component: server
          topologyKey: kubernetes.io/hostname

  extraLabels:
    region: "${region_label}"
    vault-edition: "enterprise"

  ha:
    enabled: true
    replicas: ${replica_count}
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true

        listener "tcp" {
          address         = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file   = "/vault/userconfig/vault-tls/tls.crt"
          tls_key_file    = "/vault/userconfig/vault-tls/tls.key"
          tls_client_ca_file = "/vault/userconfig/vault-tls/ca.crt"

          telemetry {
            unauthenticated_metrics_access = "true"
          }
        }

        storage "raft" {
          path = "/vault/data"

          retry_join {
            leader_api_addr         = "https://vault-0.vault-internal:8200"
            leader_ca_cert_file     = "/vault/userconfig/vault-tls/ca.crt"
            leader_client_cert_file = "/vault/userconfig/vault-tls/tls.crt"
            leader_client_key_file  = "/vault/userconfig/vault-tls/tls.key"
          }
          retry_join {
            leader_api_addr         = "https://vault-1.vault-internal:8200"
            leader_ca_cert_file     = "/vault/userconfig/vault-tls/ca.crt"
            leader_client_cert_file = "/vault/userconfig/vault-tls/tls.crt"
            leader_client_key_file  = "/vault/userconfig/vault-tls/tls.key"
          }
          retry_join {
            leader_api_addr         = "https://vault-2.vault-internal:8200"
            leader_ca_cert_file     = "/vault/userconfig/vault-tls/ca.crt"
            leader_client_cert_file = "/vault/userconfig/vault-tls/tls.crt"
            leader_client_key_file  = "/vault/userconfig/vault-tls/tls.key"
          }

          autopilot {
            cleanup_dead_servers           = "true"
            last_contact_threshold         = "200ms"
            last_contact_failure_threshold = "10m"
            max_trailing_logs              = 250000
            min_quorum                     = 3
            server_stabilization_time      = "10s"
          }
        }

        seal "azurekeyvault" {
          tenant_id  = "${akv_tenant_id}"
          vault_name = "${akv_vault_name}"
          key_name   = "${akv_key_name}"
          # Explicitly specifies which managed identity to use — required when
          # the node has multiple identities (AKS system + kubelet + others).
          client_id  = "${akv_client_id}"
        }

        telemetry {
          prometheus_retention_time = "30s"
          disable_hostname          = true
        }

        service_registration "kubernetes" {}

        %{ if replication_enabled ~}
        replication {
          resolver_discover_servers = true
        }
        %{ endif ~}

        # cluster_addr advertises the address peers use for Raft and replication
        # on port 8201. Uses a dedicated Public IP separate from the API LB.
        cluster_addr = "https://${cluster_lb_ip}:8201"
        api_addr     = "https://${lb_ip}:8200"

  auditStorage:
    enabled: true
    size: 10Gi
    storageClass: managed-csi-premium
    accessMode: ReadWriteOnce

  dataStorage:
    enabled: true
    size: 50Gi
    storageClass: managed-csi-premium
    accessMode: ReadWriteOnce

  serviceAccount:
    create: true
    annotations: {}

  serviceMonitor:
    enabled: true
    interval: "30s"
    scrapeTimeout: "10s"

ui:
  enabled: true
  serviceType: "LoadBalancer"
  serviceNodePort: null
  externalPort: 8200
  loadBalancerIP: "${lb_ip}"
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
    service.beta.kubernetes.io/azure-pip-name: "vault-ui-pip-${region_label}"
